const err = new Error(' This is an error message')

console.error(err.message)

//  Can't use try/catch blocks on asyncronous functions that throw an error
